name: "Bot notify ronin pricing"
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  notify-test:
    runs-on: ubuntu-latest
    steps:
    - run: ./jobs/ronin-notify-by-percent.sh
    env:
      TELEGRAM_CHAT_ID: '-999154067' # Anh DAP CHAI TEST
      NOTIFY_PERCENT: '0.0'