name: "Bot notify ronin pricing 1h"
on:
  schedule:
  - cron: "0 9,14,17,21 * * *"

jobs:
  notify-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./jobs/ronin-notify.sh
    env:
      TELEGRAM_CHAT_ID: '-999154067' # Anh DAP CHAI TEST
      TELEGRAM_BOT_TOKEN: {{ secret.TELEGRAM_BOT_TOKEN }}