name: "Bot notify ronin pricing at time"
on:
  schedule:
  - cron: "0 2,5,8,10,14,16 * * *"

jobs:
  notify-ronin-at-time:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./jobs/ronin-notify.sh
    env:
      TELEGRAM_CHAT_ID: '-1001318480244' # Hom nay ban da an cung Vi chua?
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
