name: "Bot notify ronin by last price"
on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  notify-ronin-by-last-price-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jorgebg/stateful-action@v0.1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: ./jobs/ronin-notify-by-last-price.sh
    env:
      TELEGRAM_CHAT_ID: '-999154067' # Anh DAP CHAI TEST
      NOTIFY_PERCENT: '10.0'
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}