name: "Bot notify ronin pricing"
on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - run: ./jobs/ronin-notify-10-percent.sh
    env:
      TELEGRAM_CHAT_ID: '-999154067' # Anh DAP CHAI TEST
      NOTIFY_PERCENT: '10.0'
    