name: "Bot notify ronin pricing"
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  notify-ronin-by-percent-gfbaby:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: ./jobs/ronin-notify-by-percent.sh
    env:
      TELEGRAM_CHAT_ID: '-1001318480244' # Hom nay ban da an cung Vi chua?
      NOTIFY_PERCENT: '10.0'
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  notify-ronin-by-percent-sm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: ./jobs/ronin-notify-by-percent.sh
    env:
      TELEGRAM_CHAT_ID: '-649357836' # SRE bau troi?
      NOTIFY_PERCENT: '10.0'
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}