name: "Bot notify ronin pricing"
on:
  push:
    branches:
      - main

jobs:
  notify-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: shogo82148/actions-setup-redis@v1
      with:
        auto-start: "false"
    - run: ./jobs/ronin-notify-by-last-price.sh
    env:
      TELEGRAM_CHAT_ID: '-999154067' # Anh DAP CHAI TEST
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
      NOTIFY_PERCENT: '0.0'